version: "3"

volumes:
  db-data:
  backend-bundle:
  backend-vendor:
  backend-tmp:

services:
  db:
    image: postgres:14
    container_name: tutorial_db
    volumes:
      - db-data:/var/lib/postgresql/tutorial_data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  tutorial:
    build:
      dockerfile: Dockerfile.dev
    container_name: tutorial
    ports:
      - "8080:8080"
    command: > # 残っているかもしれないプロセスを消してから立ち上げる
      /bin/sh -c "rm -f tmp/pids/server.pid &&
      bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      # コンテナのグローバルにインストールされたgemを、Docker Volumeにキャッシュとして保存する
      - backend-bundle:/usr/local/bundle
      # アプリケーションのソースコードをコンテナにマウントする
      - .:/tutorial-app
      # 以下はパフォーマンスのためローカルをマウントしない
      - backend-vendor:/tutorial-app/vendor
    environment:
      BACKEND_TEMP_ROOT_URL: ${BACKEND_TEMP_ROOT_URL:-http://localhost:8080} # Option
    depends_on:
      - db
    tty: true
    stdin_open: true
